name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Scala
        uses: olafurpg/setup-scala@v12
        with:
          java-version: "adopt@1.8"

      - name: Coursier cache
        uses: coursier/cache-action@v6

      - name: Check format
        run: |
          mkdir -p dist
          sbt -no-colors checkAll > dist/result.txt

      - name: Run tests
        run: sbt test

      - name: Upload sbt result
        uses: actions/upload-artifact@master
        with:
          name: sbt-result
          path: dist

  notify-success:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # - uses: actions/download-artifact@v2
      #   with:
      #     name: sbt-result
      #     path: dist

      # - run: echo ::set-output name=lines::$(grep "warn" dist/result.txt)
      #   id: warnings
      #   shell: bash

      - name: Notify to Typetalk if success
        uses: shomatan/typetalk-action@master
        env:
          TYPETALK_TOKEN: ${{ secrets.TYPETALK_TOKEN }}
        with:
          topic-id: 54145
          message: ":tada: Backlog migration common job success :smile:\n${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"

  notify-failure:
    runs-on: ubuntu-latest
    if: failure()
    needs: build

    steps:
      - name: Notify to Typetalk if fail
        uses: shomatan/typetalk-action@master
        env:
          TYPETALK_TOKEN: ${{ secrets.TYPETALK_TOKEN }}
        with:
          topic-id: 54145
          message: ":rage: Backlog migration common job failed\n${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"

  notify-cancel:
    runs-on: ubuntu-latest
    if: cancelled()
    needs: build

    steps:
      - name: Notify to Typetalk if cancelled
        uses: shomatan/typetalk-action@master
        env:
          TYPETALK_TOKEN: ${{ secrets.TYPETALK_TOKEN }}
        with:
          topic-id: 54145
          message: ":no_entry: Backlog migration common job cancelled\n${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"

