name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Scala
        uses: olafurpg/setup-scala@v12
        with:
          java-version: "adopt@1.11"

      - name: Coursier cache
        uses: coursier/cache-action@v6

      - name: Check format
        run: |
          mkdir -p dist
          sbt -no-colors checkAll > dist/result.txt

      - name: Run tests
        run: sbt test

      - name: Upload sbt result
        uses: actions/upload-artifact@master
        with:
          name: sbt-result
          path: dist
